version: '3.8'

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb-data:/var/lib/influxdb2
      - ./influxdb-config:/etc/influxdb2
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
      - INFLUXDB_ORG=yllu
      - INFLUXDB_BUCKET=yllu
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - influxdb
    restart: unless-stopped

    entrypoint: >
      sh -c "
      /run.sh &
      sleep 10 &&
      curl -X POST http://admin:admin123@localhost:3000/api/datasources \
      -H 'Content-Type: application/json' \
      -d '{\"name\": \"InfluxDB\",
            \"type\": \"influxdb\",
            \"access\": \"proxy\",
            \"url\": \"http://influxdb:8086\",
            \"jsonData\": {
              \"version\": \"Flux\",
              \"organization\": \"yllu\",
              \"defaultBucket\": \"yllu\"
            },
            \"secureJsonData\": {
              \"token\": \"nVePJnSrUJrU4lEtoSUcoEIPMvCo_0Dxw-JIL2pbak-vukX4XQJpzflevHvUPxJTOwgXnwBFMc36MLNXJtYH_Q==\"
            }}' &&
      wait"
